### ISSUE TITLE
[BUG] Unable to Log in.

### ISSUE THREAD

**Issue by Auries** [Nensec/FRTools#5] opened 2019-03-15 06:37 UTC
**Describe the bug**
I was trying to log in to Skin Tester and It wouldn't let me log in. I attempted to use the Tumblr login and Google Login and both yielding the same response.

I clicked on Tumblr log-in first, It redirected me appropriately to the Tumblr permissions page to allow the login but after clicking "Allow" it returned me back to the login page without logging me in. This also happened with the Google Login.

It seems also, that there's no way of creating an account without logging in with the socials. It would be nice to make an account which didn't need to be/wasn't linked to those profiles.

**Comment by Nensec** [comment] 2019-03-15 10:14
I did get to re-create it on the live website myself last night, but replicating it locally turned out to be fruitless. I've added some more feedback messages to help track down the issue of this while I work on improving logging. The build-in logging on my Azure host does not seem to catch the errors that are occurring here, so at this point I am blind as to what the issue is. However after I updated the live website with these feedback messages I was no longer able to replicate the issue and I could log in just fine with any provider. So at this point, all I can ask is to try again and perhaps if the same error occurs again I can narrow it down.

The choice to not have local accounts on the site was deliberate so I didn't have to make an entire infrastructure that deals with the passwords, recovery, email, etc. By using oauth providers I am keeping sensitive data off my server. It is unlikely I will add local accounts for that reason. Logging in with an external provider is merely meant as authentication, there isn't really much linking going on. On the providers that allowed me to control over what permissions to ask I made sure to dial them as low as possible, but providers like Tumblr simply provide no such control.

**Comment by Auries** [comment] 2019-03-15 10:59
So I just tried logging in again and it refused tumblr, but it allowed me to login with Google! The message I received was:
"Could not retrieve external login information from request." (From Tumblr attempt)

And re: local accounts, that does make a lot of sense and I'm sure many would be worried about information storing so I'm glad that having the external authentication does not do that. It definitely makes sense.

**Comment by Nensec** [comment] 2019-03-15 11:55
Thanks for that info. I will see if I can further replicate the issue however the line of code that throws this error doesn't really have any means for me to change how it behaves since it is a piece of framework code.. Will need to dig a little deeper, but I am glad you managed to log in just fine with Google at least.

You can unsubscribe from this issue if you wish, since I will keep progress updates in here but they (should) no longer concern you since you are logged in.

**Comment by Akaineko-astasi** [comment] 2019-03-24 00:35
Not even sure what happened or should I make a separate issue for this. 

I went to login page, chose Twitter. 
It asked me if I want to autorise the site, I clicked Yes. 
I've been redirected to FRTester's Home Page with "Could not retrieve external login information from request" error. 
I clicked the Login next time, login was painless and OK.

Now I log out and log in with Twitter just fine.

**Comment by Nensec** [comment] 2019-03-24 00:52
That is very helpful information, thanks!

**Comment by Nensec** [comment] 2019-04-26 05:28
Seems this issue is still persisting, as I just encountered it myself. However simply trying again worked just fine. Need to do some more digging into this one.

**Comment by Nensec** [comment] 2020-05-01 01:02
The latest update that went live possible fixed this, let me know if it _still_ persists x.x

**Comment by Nensec** [comment] 2020-05-17 01:17
Closing this for now, if login issues resurface will re-open it

**Closed by Nensec** 2020-05-17 01:17 UTC
Labels: bug
